[2023-11-02T17:10:03.343+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: good_morning_1.say_hello scheduled__2023-11-02T16:10:00+00:00 [queued]>
[2023-11-02T17:10:03.360+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: good_morning_1.say_hello scheduled__2023-11-02T16:10:00+00:00 [queued]>
[2023-11-02T17:10:03.361+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-02T17:10:03.388+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): say_hello> on 2023-11-02 16:10:00+00:00
[2023-11-02T17:10:03.401+0000] {standard_task_runner.py:57} INFO - Started process 2574 to run task
[2023-11-02T17:10:03.406+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'good_morning_1', 'say_hello', 'scheduled__2023-11-02T16:10:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/good_mornig.py', '--cfg-path', '/tmp/tmpk_ecp8k5']
[2023-11-02T17:10:03.411+0000] {standard_task_runner.py:85} INFO - Job 11: Subtask say_hello
[2023-11-02T17:10:03.487+0000] {task_command.py:416} INFO - Running <TaskInstance: good_morning_1.say_hello scheduled__2023-11-02T16:10:00+00:00 [running]> on host 92cf584970c8
[2023-11-02T17:10:03.605+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mdv' AIRFLOW_CTX_DAG_ID='good_morning_1' AIRFLOW_CTX_TASK_ID='say_hello' AIRFLOW_CTX_EXECUTION_DATE='2023-11-02T16:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-02T16:10:00+00:00'
[2023-11-02T17:10:03.609+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-02T17:10:03.611+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker info']
[2023-11-02T17:10:03.636+0000] {subprocess.py:86} INFO - Output:
[2023-11-02T17:10:03.670+0000] {subprocess.py:93} INFO - Client:
[2023-11-02T17:10:03.671+0000] {subprocess.py:93} INFO -  Context:    default
[2023-11-02T17:10:03.671+0000] {subprocess.py:93} INFO -  Debug Mode: false
[2023-11-02T17:10:03.672+0000] {subprocess.py:93} INFO - 
[2023-11-02T17:10:03.673+0000] {subprocess.py:93} INFO - Server:
[2023-11-02T17:10:03.674+0000] {subprocess.py:93} INFO - ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2023-11-02T17:10:03.675+0000] {subprocess.py:93} INFO - errors pretty printing info
[2023-11-02T17:10:03.676+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-02T17:10:03.693+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-02T17:10:03.699+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=good_morning_1, task_id=say_hello, execution_date=20231102T161000, start_date=20231102T171003, end_date=20231102T171003
[2023-11-02T17:10:03.719+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 11 for task say_hello (Bash command failed. The command returned a non-zero exit code 1.; 2574)
[2023-11-02T17:10:03.739+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-02T17:10:03.779+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
