[2023-11-01T18:28:22.901+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: good_morning_1.say_hello manual__2023-11-01T18:27:17.080729+00:00 [queued]>
[2023-11-01T18:28:22.922+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: good_morning_1.say_hello manual__2023-11-01T18:27:17.080729+00:00 [queued]>
[2023-11-01T18:28:22.923+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-01T18:28:22.942+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): say_hello> on 2023-11-01 18:27:17.080729+00:00
[2023-11-01T18:28:22.954+0000] {standard_task_runner.py:57} INFO - Started process 6987 to run task
[2023-11-01T18:28:22.958+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'good_morning_1', 'say_hello', 'manual__2023-11-01T18:27:17.080729+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/good_mornig.py', '--cfg-path', '/tmp/tmpwtpmdg7k']
[2023-11-01T18:28:22.962+0000] {standard_task_runner.py:85} INFO - Job 47: Subtask say_hello
[2023-11-01T18:28:23.029+0000] {task_command.py:416} INFO - Running <TaskInstance: good_morning_1.say_hello manual__2023-11-01T18:27:17.080729+00:00 [running]> on host cc3c0240a654
[2023-11-01T18:28:23.145+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mdv' AIRFLOW_CTX_DAG_ID='good_morning_1' AIRFLOW_CTX_TASK_ID='say_hello' AIRFLOW_CTX_EXECUTION_DATE='2023-11-01T18:27:17.080729+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-01T18:27:17.080729+00:00'
[2023-11-01T18:28:23.148+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-01T18:28:23.149+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker info']
[2023-11-01T18:28:23.170+0000] {subprocess.py:86} INFO - Output:
[2023-11-01T18:28:23.197+0000] {subprocess.py:93} INFO - Client:
[2023-11-01T18:28:23.198+0000] {subprocess.py:93} INFO -  Context:    default
[2023-11-01T18:28:23.199+0000] {subprocess.py:93} INFO -  Debug Mode: false
[2023-11-01T18:28:23.200+0000] {subprocess.py:93} INFO - 
[2023-11-01T18:28:23.201+0000] {subprocess.py:93} INFO - Server:
[2023-11-01T18:28:23.202+0000] {subprocess.py:93} INFO - ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2023-11-01T18:28:23.203+0000] {subprocess.py:93} INFO - errors pretty printing info
[2023-11-01T18:28:23.204+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-01T18:28:23.221+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-01T18:28:23.227+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=good_morning_1, task_id=say_hello, execution_date=20231101T182717, start_date=20231101T182822, end_date=20231101T182823
[2023-11-01T18:28:23.247+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 47 for task say_hello (Bash command failed. The command returned a non-zero exit code 1.; 6987)
[2023-11-01T18:28:23.291+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-01T18:28:23.345+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
