[2023-11-03T19:42:40.427+0000] {processor.py:157} INFO - Started process (PID=33484) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:42:40.431+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:42:40.444+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:42:40.443+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:42:40.546+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:42:40.537+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:42:40.550+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:42:40.634+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.220 seconds
[2023-11-03T19:43:10.778+0000] {processor.py:157} INFO - Started process (PID=33545) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:43:10.781+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:43:10.789+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:43:10.787+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:43:10.840+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:43:10.837+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:43:10.843+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:43:10.885+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.116 seconds
[2023-11-03T19:43:41.698+0000] {processor.py:157} INFO - Started process (PID=33607) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:43:41.700+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:43:41.708+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:43:41.707+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:43:41.753+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:43:41.748+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:43:41.755+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:43:41.785+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.098 seconds
[2023-11-03T19:44:12.376+0000] {processor.py:157} INFO - Started process (PID=33669) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:44:12.379+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:44:12.389+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:44:12.387+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:44:12.445+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:44:12.441+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:44:12.447+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:44:12.474+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.108 seconds
[2023-11-03T19:44:42.689+0000] {processor.py:157} INFO - Started process (PID=33731) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:44:42.692+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:44:42.700+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:44:42.699+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:44:42.758+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:44:42.752+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:44:42.761+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:44:42.788+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.108 seconds
[2023-11-03T19:45:12.864+0000] {processor.py:157} INFO - Started process (PID=33793) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:45:12.867+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:45:12.877+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:45:12.875+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:45:12.926+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:45:12.923+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:45:12.929+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:45:12.964+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.111 seconds
[2023-11-03T19:45:43.619+0000] {processor.py:157} INFO - Started process (PID=33855) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:45:43.622+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:45:43.633+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:45:43.631+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:45:43.694+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:45:43.688+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:45:43.698+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:45:43.767+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.158 seconds
[2023-11-03T19:46:14.237+0000] {processor.py:157} INFO - Started process (PID=33917) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:46:14.241+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:46:14.248+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:46:14.247+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:46:14.303+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:46:14.299+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:46:14.305+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:46:14.339+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.113 seconds
[2023-11-03T19:46:44.642+0000] {processor.py:157} INFO - Started process (PID=33979) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:46:44.644+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:46:44.652+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:46:44.650+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:46:44.717+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:46:44.713+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:46:44.719+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:46:44.748+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.114 seconds
[2023-11-03T19:47:15.140+0000] {processor.py:157} INFO - Started process (PID=34041) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:47:15.142+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:47:15.149+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:47:15.148+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:47:15.208+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:47:15.201+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:47:15.211+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:47:15.251+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.118 seconds
[2023-11-03T19:47:46.015+0000] {processor.py:157} INFO - Started process (PID=34103) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:47:46.018+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:47:46.024+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:47:46.023+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:47:46.069+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:47:46.066+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:47:46.071+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:47:46.126+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.118 seconds
[2023-11-03T19:48:16.342+0000] {processor.py:157} INFO - Started process (PID=34165) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:48:16.344+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:48:16.351+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:48:16.350+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:48:16.401+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:48:16.398+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:48:16.404+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:48:16.436+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.102 seconds
[2023-11-03T19:48:47.000+0000] {processor.py:157} INFO - Started process (PID=34227) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:48:47.003+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:48:47.013+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:48:47.011+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:48:47.068+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:48:47.064+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:48:47.070+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:48:47.111+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.120 seconds
[2023-11-03T19:49:18.041+0000] {processor.py:157} INFO - Started process (PID=34290) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:49:18.044+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:49:18.052+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:49:18.050+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:49:18.107+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:49:18.104+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:49:18.111+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:49:18.146+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.112 seconds
[2023-11-03T19:49:48.342+0000] {processor.py:157} INFO - Started process (PID=34352) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:49:48.345+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:49:48.351+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:49:48.350+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:49:48.419+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:49:48.414+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:49:48.422+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:49:48.455+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.121 seconds
[2023-11-03T19:50:19.217+0000] {processor.py:157} INFO - Started process (PID=34414) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:50:19.219+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:50:19.226+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:50:19.225+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:50:19.279+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:50:19.274+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:50:19.280+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:50:19.312+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.105 seconds
[2023-11-03T19:50:50.423+0000] {processor.py:157} INFO - Started process (PID=34477) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:50:50.426+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:50:50.433+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:50:50.432+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:50:50.481+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:50:50.477+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:50:50.483+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:50:50.513+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.098 seconds
[2023-11-03T19:51:21.275+0000] {processor.py:157} INFO - Started process (PID=34539) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:51:21.278+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:51:21.286+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:51:21.285+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:51:21.332+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:51:21.329+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:51:21.334+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:51:21.361+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.094 seconds
[2023-11-03T19:51:51.625+0000] {processor.py:157} INFO - Started process (PID=34601) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:51:51.630+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:51:51.639+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:51:51.638+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:51:51.703+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:51:51.693+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:51:51.706+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:51:51.763+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.150 seconds
[2023-11-03T19:52:22.202+0000] {processor.py:157} INFO - Started process (PID=34662) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:52:22.205+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:52:22.214+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:52:22.213+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:52:22.263+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:52:22.259+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:52:22.265+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:52:22.299+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.114 seconds
[2023-11-03T19:52:52.684+0000] {processor.py:157} INFO - Started process (PID=34724) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:52:52.686+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:52:52.694+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:52:52.692+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:52:52.743+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:52:52.739+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:52:52.746+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:52:52.775+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.099 seconds
[2023-11-03T19:53:23.148+0000] {processor.py:157} INFO - Started process (PID=34786) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:53:23.151+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:53:23.158+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:53:23.157+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:53:23.213+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:53:23.209+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:53:23.215+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:53:23.255+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.113 seconds
[2023-11-03T19:53:53.566+0000] {processor.py:157} INFO - Started process (PID=34848) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:53:53.569+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:53:53.576+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:53:53.574+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:53:53.620+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:53:53.616+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:53:53.621+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:53:53.647+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.091 seconds
[2023-11-03T19:54:24.259+0000] {processor.py:157} INFO - Started process (PID=34910) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:54:24.261+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:54:24.268+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:54:24.267+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:54:24.316+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:54:24.312+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:54:24.318+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:54:24.351+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.099 seconds
[2023-11-03T19:54:54.622+0000] {processor.py:157} INFO - Started process (PID=34972) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:54:54.625+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:54:54.631+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:54:54.630+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:54:54.686+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:54:54.682+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:54:54.688+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:54:54.718+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.102 seconds
[2023-11-03T19:55:24.940+0000] {processor.py:157} INFO - Started process (PID=35034) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:55:24.943+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:55:24.952+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:55:24.950+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:55:24.993+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:55:24.990+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:55:24.995+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:55:25.021+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.092 seconds
[2023-11-03T19:55:55.471+0000] {processor.py:157} INFO - Started process (PID=35096) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:55:55.474+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:55:55.482+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:55:55.480+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:55:55.541+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:55:55.536+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:55:55.543+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:55:55.582+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.119 seconds
[2023-11-03T19:56:26.160+0000] {processor.py:157} INFO - Started process (PID=35158) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:56:26.163+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:56:26.170+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:56:26.169+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:56:26.213+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:56:26.210+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:56:26.216+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:56:26.247+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.095 seconds
[2023-11-03T19:56:57.492+0000] {processor.py:157} INFO - Started process (PID=35221) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:56:57.496+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:56:57.504+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:56:57.502+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:56:57.554+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:56:57.550+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:56:57.555+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:56:57.580+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.097 seconds
[2023-11-03T19:57:28.215+0000] {processor.py:157} INFO - Started process (PID=35283) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:57:28.218+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:57:28.225+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:57:28.223+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:57:28.273+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:57:28.270+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:57:28.276+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:57:28.301+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.094 seconds
[2023-11-03T19:57:58.540+0000] {processor.py:157} INFO - Started process (PID=35345) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:57:58.542+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:57:58.548+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:57:58.547+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:57:58.591+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:57:58.588+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:57:58.593+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:57:58.618+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.087 seconds
[2023-11-03T19:58:28.698+0000] {processor.py:157} INFO - Started process (PID=35407) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:58:28.701+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:58:28.708+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:58:28.706+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:58:28.755+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:58:28.751+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:58:28.757+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:58:28.785+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.095 seconds
[2023-11-03T19:58:59.561+0000] {processor.py:157} INFO - Started process (PID=35469) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:58:59.564+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:58:59.571+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:58:59.569+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:58:59.616+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:58:59.613+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:58:59.618+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:58:59.645+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.093 seconds
[2023-11-03T19:59:30.075+0000] {processor.py:157} INFO - Started process (PID=35528) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:59:30.078+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T19:59:30.086+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:59:30.084+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:59:30.138+0000] {logging_mixin.py:151} INFO - [2023-11-03T19:59:30.134+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T19:59:30.140+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T19:59:30.173+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.108 seconds
[2023-11-03T20:00:00.781+0000] {processor.py:157} INFO - Started process (PID=35590) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:00:00.784+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T20:00:00.791+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:00:00.790+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:00:00.847+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:00:00.842+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T20:00:00.850+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:00:00.875+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.102 seconds
[2023-11-03T20:00:31.451+0000] {processor.py:157} INFO - Started process (PID=35652) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:00:31.455+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T20:00:31.464+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:00:31.463+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:00:31.529+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:00:31.524+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T20:00:31.531+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:00:31.563+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.122 seconds
[2023-11-03T20:01:01.934+0000] {processor.py:157} INFO - Started process (PID=35712) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:01:01.937+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T20:01:01.952+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:01:01.950+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:01:02.015+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:01:02.011+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T20:01:02.018+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:01:02.052+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.128 seconds
[2023-11-03T20:01:32.331+0000] {processor.py:157} INFO - Started process (PID=35774) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:01:32.333+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T20:01:32.340+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:01:32.339+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:01:32.387+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:01:32.384+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T20:01:32.389+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:01:32.423+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.099 seconds
[2023-11-03T20:02:02.822+0000] {processor.py:157} INFO - Started process (PID=35836) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:02:02.825+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T20:02:02.834+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:02:02.833+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:02:02.881+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:02:02.878+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T20:02:02.883+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:02:02.912+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.098 seconds
[2023-11-03T20:02:33.618+0000] {processor.py:157} INFO - Started process (PID=35896) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:02:33.621+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T20:02:33.631+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:02:33.629+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:02:33.683+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:02:33.677+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T20:02:33.686+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:02:33.719+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.109 seconds
[2023-11-03T20:03:04.213+0000] {processor.py:157} INFO - Started process (PID=35958) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:03:04.216+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T20:03:04.223+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:03:04.222+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:03:04.277+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:03:04.274+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T20:03:04.280+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:03:04.312+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.109 seconds
[2023-11-03T20:03:34.645+0000] {processor.py:157} INFO - Started process (PID=36020) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:03:34.647+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T20:03:34.654+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:03:34.653+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:03:34.698+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:03:34.695+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T20:03:34.700+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:03:34.726+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.089 seconds
[2023-11-03T20:04:05.308+0000] {processor.py:157} INFO - Started process (PID=36082) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:04:05.311+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T20:04:05.317+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:04:05.316+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:04:05.370+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:04:05.365+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T20:04:05.372+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:04:05.414+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.114 seconds
[2023-11-03T20:04:36.174+0000] {processor.py:157} INFO - Started process (PID=36143) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:04:36.177+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T20:04:36.185+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:04:36.184+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:04:36.235+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:04:36.231+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T20:04:36.236+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:04:36.263+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.096 seconds
[2023-11-03T20:05:06.957+0000] {processor.py:157} INFO - Started process (PID=36205) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:05:06.960+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T20:05:06.968+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:05:06.967+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:05:07.020+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:05:07.018+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T20:05:07.022+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:05:07.049+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.102 seconds
[2023-11-03T20:05:37.407+0000] {processor.py:157} INFO - Started process (PID=36267) to work on /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:05:37.409+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/06_branch_example.py for tasks to queue
[2023-11-03T20:05:37.416+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:05:37.415+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:05:37.471+0000] {logging_mixin.py:151} INFO - [2023-11-03T20:05:37.466+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/06_branch_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/06_branch_example.py", line 11, in <module>
    filename = Path(Variable.get("input_file"))
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 140, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable input_file does not exist'
[2023-11-03T20:05:37.475+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/06_branch_example.py
[2023-11-03T20:05:37.509+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/06_branch_example.py took 0.111 seconds
