[2023-11-01T18:27:20.381+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: good_morning_1.say_hello manual__2023-11-01T18:27:17.080729+00:00 [queued]>
[2023-11-01T18:27:20.397+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: good_morning_1.say_hello manual__2023-11-01T18:27:17.080729+00:00 [queued]>
[2023-11-01T18:27:20.398+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-01T18:27:20.424+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): say_hello> on 2023-11-01 18:27:17.080729+00:00
[2023-11-01T18:27:20.437+0000] {standard_task_runner.py:57} INFO - Started process 6957 to run task
[2023-11-01T18:27:20.442+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'good_morning_1', 'say_hello', 'manual__2023-11-01T18:27:17.080729+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/good_mornig.py', '--cfg-path', '/tmp/tmpqs5xxpxj']
[2023-11-01T18:27:20.446+0000] {standard_task_runner.py:85} INFO - Job 46: Subtask say_hello
[2023-11-01T18:27:20.515+0000] {task_command.py:416} INFO - Running <TaskInstance: good_morning_1.say_hello manual__2023-11-01T18:27:17.080729+00:00 [running]> on host cc3c0240a654
[2023-11-01T18:27:20.673+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mdv' AIRFLOW_CTX_DAG_ID='good_morning_1' AIRFLOW_CTX_TASK_ID='say_hello' AIRFLOW_CTX_EXECUTION_DATE='2023-11-01T18:27:17.080729+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-01T18:27:17.080729+00:00'
[2023-11-01T18:27:20.676+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-01T18:27:20.678+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker info']
[2023-11-01T18:27:20.700+0000] {subprocess.py:86} INFO - Output:
[2023-11-01T18:27:20.726+0000] {subprocess.py:93} INFO - Client:
[2023-11-01T18:27:20.727+0000] {subprocess.py:93} INFO -  Context:    default
[2023-11-01T18:27:20.728+0000] {subprocess.py:93} INFO -  Debug Mode: false
[2023-11-01T18:27:20.728+0000] {subprocess.py:93} INFO - 
[2023-11-01T18:27:20.730+0000] {subprocess.py:93} INFO - Server:
[2023-11-01T18:27:20.730+0000] {subprocess.py:93} INFO - ERROR: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
[2023-11-01T18:27:20.731+0000] {subprocess.py:93} INFO - errors pretty printing info
[2023-11-01T18:27:20.734+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-01T18:27:20.751+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-01T18:27:20.758+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=good_morning_1, task_id=say_hello, execution_date=20231101T182717, start_date=20231101T182720, end_date=20231101T182720
[2023-11-01T18:27:20.778+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 46 for task say_hello (Bash command failed. The command returned a non-zero exit code 1.; 6957)
[2023-11-01T18:27:20.815+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-01T18:27:20.879+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
